"""order deets

Revision ID: 227ca3a4518e
Revises: 909166515945
Create Date: 2020-07-03 16:50:47.221678

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '227ca3a4518e'
down_revision = '909166515945'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order_details', sa.Column('address', sa.String(), nullable=False))
    op.add_column('order_details', sa.Column('payerID', sa.Integer(), nullable=False))
    op.drop_column('order_details', 'seller_id')
    op.drop_column('order_details', 'buyer_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order_details', sa.Column('buyer_id', sa.INTEGER(), nullable=False))
    op.add_column('order_details', sa.Column('seller_id', sa.INTEGER(), nullable=False))
    op.drop_column('order_details', 'payerID')
    op.drop_column('order_details', 'address')
    # ### end Alembic commands ###
