"""graph

Revision ID: 47aeb2759b83
Revises: 
Create Date: 2020-07-01 20:47:11.269159

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '47aeb2759b83'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('warehouse')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('warehouse',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('x', sa.FLOAT(), nullable=True),
    sa.Column('y', sa.FLOAT(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
