"""warehouse table

Revision ID: 6e440f8be838
Revises: 2909f66f7de9
Create Date: 2020-07-02 13:07:27.321128

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6e440f8be838'
down_revision = '2909f66f7de9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('warehouse', sa.Column('email', sa.String(length=120), nullable=False))
    op.add_column('warehouse', sa.Column('name', sa.String(length=20), nullable=False))
    op.add_column('warehouse', sa.Column('password', sa.String(length=60), nullable=False))
    op.create_unique_constraint(None, 'warehouse', ['email'])
    op.create_unique_constraint(None, 'warehouse', ['name'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'warehouse', type_='unique')
    op.drop_constraint(None, 'warehouse', type_='unique')
    op.drop_column('warehouse', 'password')
    op.drop_column('warehouse', 'name')
    op.drop_column('warehouse', 'email')
    # ### end Alembic commands ###
