"""order deets

Revision ID: 8d708e1e2f94
Revises: 227ca3a4518e
Create Date: 2020-07-03 17:59:16.880086

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8d708e1e2f94'
down_revision = '227ca3a4518e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order_details', sa.Column('paymentID', sa.String(), nullable=False))
    op.create_unique_constraint(None, 'order_details', ['paymentID'])
    op.drop_column('order_details', 'payerID')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order_details', sa.Column('payerID', sa.INTEGER(), nullable=False))
    op.drop_constraint(None, 'order_details', type_='unique')
    op.drop_column('order_details', 'paymentID')
    # ### end Alembic commands ###
