"""users table

Revision ID: 909166515945
Revises: b2c6f3ea619f
Create Date: 2020-07-03 15:17:12.723653

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '909166515945'
down_revision = 'b2c6f3ea619f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('warehouse',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=20), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password', sa.String(length=60), nullable=False),
    sa.Column('location', sa.String(length=60), nullable=False),
    sa.Column('x', sa.Float(), nullable=True),
    sa.Column('y', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('name')
    )
    op.create_table('edges',
    sa.Column('node_1', sa.Integer(), nullable=True),
    sa.Column('node_2', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['node_1'], ['warehouse.id'], ),
    sa.ForeignKeyConstraint(['node_2'], ['warehouse.id'], )
    )
    op.create_table('order_details',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('buyer_id', sa.Integer(), nullable=False),
    sa.Column('seller_id', sa.Integer(), nullable=False),
    sa.Column('current_warehouse_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['current_warehouse_id'], ['warehouse.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('order_details')
    op.drop_table('edges')
    op.drop_table('warehouse')
    # ### end Alembic commands ###
