"""graph

Revision ID: cb977e5b766f
Revises: 47aeb2759b83
Create Date: 2020-07-01 21:01:41.970424

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cb977e5b766f'
down_revision = '47aeb2759b83'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('warehouse')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('warehouse',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('x', sa.FLOAT(), nullable=True),
    sa.Column('y', sa.FLOAT(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
