"""graph

Revision ID: dd914d78b070
Revises: cb977e5b766f
Create Date: 2020-07-01 22:07:40.088834

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dd914d78b070'
down_revision = 'cb977e5b766f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('edges')
    op.drop_table('warehouse')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('warehouse',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('x', sa.FLOAT(), nullable=True),
    sa.Column('y', sa.FLOAT(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('edges',
    sa.Column('node_1', sa.INTEGER(), nullable=True),
    sa.Column('node_2', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['node_1'], ['warehouse.id'], ),
    sa.ForeignKeyConstraint(['node_2'], ['warehouse.id'], )
    )
    # ### end Alembic commands ###
