"""warehouse table

Revision ID: f351f2ea8290
Revises: 9d3ccde46bf3
Create Date: 2020-07-02 13:28:24.156554

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f351f2ea8290'
down_revision = '9d3ccde46bf3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('warehouse', sa.Column('email', sa.String(length=120), nullable=False))
    op.add_column('warehouse', sa.Column('name', sa.String(length=20), nullable=False))
    op.add_column('warehouse', sa.Column('password', sa.String(length=60), nullable=False))
    op.create_unique_constraint(None, 'warehouse', ['email'])
    op.create_unique_constraint(None, 'warehouse', ['name'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'warehouse', type_='unique')
    op.drop_constraint(None, 'warehouse', type_='unique')
    op.drop_column('warehouse', 'password')
    op.drop_column('warehouse', 'name')
    op.drop_column('warehouse', 'email')
    # ### end Alembic commands ###
